web/Controllers/WarehousesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;

namespace web.Controllers
{
    [Authorize]
    public class WarehousesController : Controller
    {
        private readonly WarehouseContext _context;


        public WarehousesController(WarehouseContext context)
        {
            _context = context;
        }

        // GET: Warehouses
       public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Warehouses == null)
            {
                return Problem("Entity set 'WarehouseContext.Warehouse'  is null.");

            }

            var warehouses = from w in _context.Warehouses
                        select w;

            if (!String.IsNullOrEmpty(searchString))
            {
                warehouses = warehouses.Where(s => s.WarehouseCode!.Contains(searchString));
            }

            return View(await warehouses.ToListAsync());
        }

        // GET: Warehouses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Warehouses == null)
            {
                return NotFound();
            }

            var warehouse = await _context.Warehouses
                .FirstOrDefaultAsync(m => m.WarehouseID == id);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // GET: Warehouses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Warehouses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WarehouseID,WarehouseCode,Zone,Full")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(warehouse);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(warehouse);
        }

        // GET: Warehouses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Warehouses == null)
            {
                return NotFound();
            }

            var warehouse = await _context.Warehouses.FindAsync(id);
            if (warehouse == null)
            {
                return NotFound();
            }
            return View(warehouse);
        }

        // POST: Warehouses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WarehouseID,WarehouseCode,Zone,Full")] Warehouse warehouse)
        {
            if (id != warehouse.WarehouseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(warehouse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WarehouseExists(warehouse.WarehouseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(warehouse);
        }

        // GET: Warehouses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Warehouses == null)
            {
                return NotFound();
            }

            var warehouse = await _context.Warehouses
                .FirstOrDefaultAsync(m => m.WarehouseID == id);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Warehouses == null)
            {
                return Problem("Entity set 'WarehouseContext.Warehouses'  is null.");
            }
            var warehouse = await _context.Warehouses.FindAsync(id);
            if (warehouse != null)
            {
                _context.Warehouses.Remove(warehouse);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WarehouseExists(int id)
        {
            return _context.Warehouses.Any(e => e.WarehouseID == id);
        }
    }
}

web/Views/Warehouses/Create.cshtml
@model web.Models.Warehouse

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Warehouse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WarehouseCode" class="control-label">Warehouse Code</label>
                <input asp-for="WarehouseCode" class="form-control" />
                <span asp-validation-for="WarehouseCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zone" class="control-label"></label>
                @Html.DropDownListFor(model  => model.Zone, new SelectList(Enum.GetValues(typeof(Zone))))
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Full" /> @Html.DisplayNameFor(model => model.Full)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Warehouses/Delete.cshtml
@model web.Models.Warehouse

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Warehouse Code
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WarehouseCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Full)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Full)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="WarehouseID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web/Views/Warehouses/Details.cshtml
@model web.Models.Warehouse

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Warehouse Code
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WarehouseCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Full)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Full)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.WarehouseID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Warehouses/Edit.cshtml
@model web.Models.Warehouse

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Warehouse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="WarehouseID" />
            <div class="form-group">
                <label asp-for="WarehouseCode" class="control-label">Warehouse Code</label>
                <input asp-for="WarehouseCode" class="form-control" />
                <span asp-validation-for="WarehouseCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zone" class="control-label"></label>
                <select asp-for="Zone" class="form-control"></select>
                <span asp-validation-for="Zone" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Full" /> @Html.DisplayNameFor(model => model.Full)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Warehouses/Index.cshtml
@model IEnumerable<web.Models.Warehouse>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Warehouses" asp-action="Index" >
    <p>
        Warehouse Code: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Warehouse Code
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Full)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.WarehouseCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Full)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.WarehouseID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.WarehouseID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.WarehouseID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>